---
title: "Demystify the Semester with the SDS 192 Grade Calculator"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## The Calculator 

Replace the random values in the tibble column "scores" with your actual data and make predictions for future grades.

```{r cars}
library(tidyverse)

#build the calculator and input your data in "scores"
SDS_grades <- tibble(
  coursework = c("MT1", "MT2", "MP1", "MP2", "MP3", "FP", "Pset", "ENGMNT"),
  weight = c(0.15, 0.20, 0.05, 0.10, 0.15, 0.20, 0.10, 0.05),
  scores = c(80, 95, 100, 90, 78, 90, 85, 100)) %>%
  summarize(sem_grade= sum(weight * scores)) %>%
  mutate(letter_grade= ifelse(sem_grade>92,"A",
                              ifelse(sem_grade<=92 & sem_grade>=90, "A-",
                                     ifelse(sem_grade<90 & sem_grade>=87, "B+",
                                            ifelse(sem_grade<87 & sem_grade>=83, "B",
                                                   ifelse(sem_grade<83 & sem_grade>=80, "B-",
                                                          ifelse(sem_grade<80 & sem_grade>=77, "C+",
                                                                 ifelse(sem_grade<77 & sem_grade>=73, "C",
                                                                    ifelse(sem_grade<73 & sem_grade>=70, "C-",
                                                                    ifelse(sem_grade<70 & sem_grade>=50, "DROP SDS 192"))))))))))

SDS_grades
```

```{r, echo=FALSE}
#import scale file
library(readxl)
grade_calc<-read_xlsx("data/README.xlsx")

#reorder x axis
grade_calc$letter_grade <- as.character(grade_calc$letter_grade)
grade_calc$letter_grade <- factor(grade_calc$letter_grade, levels=unique(grade_calc$letter_grade))
```

## See How You Stack Up
```{r pressure, echo=FALSE}
library(ggplot2)

ggplot() +
  geom_point(grade_calc, mapping=aes(x= letter_grade, y = high_score), size=0.5) +
  geom_point(grade_calc, mapping=aes(x= letter_grade, y= low_score), size=0.5) +
  geom_point(SDS_grades, mapping = aes(x=letter_grade, y=sem_grade), color="red", size= 2) +
  labs(
    title = "Semester Grade Forecast in SDS 192",
    subtitle = "As Shown by Red Dot",
    y="score",
    x= "letter grade")
```

